Feature/issue 13
TakumiKaribe/multilingo pull request #18
Opened 2019-02-21 16:31 UTC by 44smkn

I added logger package "logrus" and congfiguration package "envconfig".

2019-02-22 03:31 UTC, TakumiKaribe commented
My logger is deleted 😭😭😭😭😭😭😭😭

2019-02-23 07:39 UTC, TakumiKaribe commented on main.go
> +	SwiftToken      string `required:"true" split_words:"true"`
![badge](https://img.shields.io/badge/review-must-red.svg)
Kotlinがモレてる？

2019-02-23 07:39 UTC, TakumiKaribe commented on main.go
> +
![badge](https://img.shields.io/badge/review-ask-blue.svg)
この辺、もろもろ別ファイルにすることは可能？
まだ他のpackageの依存も整理しきれていないけど、今回の対応について下記のpackageがmainでimportする必要なければ、切り出しをお願いしたい。
```
"github.com/kelseyhightower/envconfig"
log "github.com/sirupsen/logrus"
```

2019-02-24 06:33 UTC, karrybit requested changes

2019-02-24 06:33 UTC, TakumiKaribe commented on main.go
> +	SwiftToken      string `required:"true" split_words:"true"`
![badge](https://img.shields.io/badge/review-imo-ff69b4.svg)
`C++`あるし`C`はいらないかもなぁ
あと、`JavascriptToken` → `JavaScriptToken`では？

2019-02-25 00:27 UTC, 44smkn commented
Sorry…  
But, I suppose you think this fix is needed.

2019-02-25 00:28 UTC, merged